### ISSUE TITLE
Update to Jetty 9.2 and latest version of Jersey

### ISSUE THREAD

**Issue by ijuma** [confluentinc/rest-utils#20]
Once #19 is merged, we can upgrade to Jetty 9.2 (9.2 requires Java 7 while 9.3 requires Java 8) and the latest version of Jersey (seems to be 2.19).

We should also consider removing `JettyTestContainer` as its documentation implies that it was only needed due to the Java 6 requirement.

**Comment by ewencp** [comment]
Fixed by #21
