### ISSUE TITLE
not able to build

### ISSUE THREAD

**Issue by zohakhan6** [confluentinc/rest-utils#39]
on executin mvn clean install ,getting 
Failed to execute goal on project rest-utils: Could not resolve dependencies for project io.confluent:rest-utils:jar:3.0.0-SNAPSHOT: The following artifacts could not be resolved: io.confluent:common-config:jar:3.0.0-SNAPSHOT, io.confluent:common-metrics:jar:3.0.0-SNAPSHOT: Failure to find io.confluent:common-config:jar:3.0.0-SNAPSHOT in http://server.development.com:8080/libs-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by miguno** [comment]
You must first build https://github.com/confluentinc/common (`master` branch) and make it available to maven, e.g. by installing it to your local maven repository (under `~/.m2` by default).

Example:

```
$ git clone git@github.com:confluentinc/common.git
$ cd common
$ git checkout master
$ mvn clean install
```

**Comment by imdark** [comment]
this also requires installing kafka snapshot to the local store currently, you should really add this documentation to the README.md

**Comment by leecarroll150** [comment]
failing to build with 
[ERROR] error: error reading ...........\.m2\repository\org\apache\kafka\ka
fka-clients\0.10.2.0-cp1\kafka-clients-0.10.2.0-cp1-test.jar; error in opening z
ip file. 
is this a windows build issue ?

**Comment by ewencp** [comment]
@leecarroll150 Unlikely, maven works fine on windows. See http://stackoverflow.com/questions/7600028/maven-error-in-opening-zip-file-when-running-maven for the likely cause -- the data for the file may have been corrupted. Just delete that file and try re-building.

**Comment by ewencp** [comment]
Also, closing as the original issue was addressed.

**Comment by ligadeprojects** [comment]
@miguno getting below error

git clone git@github.com:confluentinc/common.git
Cloning into 'common'...
ssh_exchange_identification: read: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ewencp** [comment]
@ligadeprojects that's some issue with your git setup. If you're using `git@github.com` type address, you need an SSH key setup on your github account. You can also try the https address if you don't have an SSH key, https://github.com/confluentinc/common.git

The repo is public and people regularly clone it, so aside from helping debug your git setup, not much we can do to fix this. Can you clone any other repos from github? A timeout is a bit odd, could also indicate you have connectivity issues to github or some IP ban on the github side that is affecting you.
