### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by jerryldh** [confluentinc/rest-utils#80]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.confluent:rest-utils-parent:[unknown-version]: Could not transfer artifact io.confluent:common:pom:4.0.0 from/to eapnexus (https://eapnexus.jnj.com/nexus/content/groups/public/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and 'parent.relativePath' points at wrong local POM @ line 8, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.confluent:rest-utils-parent:[unknown-version] (C:\Work\Hub\CodeHub\kafka\rest-utils\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent:rest-utils-parent:[unknown-version]: Could not transfer artifact io.confluent:common:pom:4.0.0 from/to eapnexus (https://eapnexus.jnj.com/nexus/content/groups/public/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and 'parent.relativePath' points at wrong local POM @ line 8, column 13 -> [Help 2]

**Comment by f-ld** [comment]
I got the same issue with a different version of `confluent:common:pom`:
```Could not transfer artifact io.confluent:rest-utils-parent:pom:4.1.0-SNAPSHOT from/to confluent (${confluent.maven.repo}):```

Quick solution that worked in my case:
- get a clone of this: https://github.com/confluentinc/common:
```git clone git@github.com:confluentinc/common.git```
- in your case, `git checkout` the version you need (look for releases here https://github.com/confluentinc/common/releases)
- install it locally:
```mvn install```
And then you can try again to build your project. It should get fixed.

Explanation: this build looks for dependencies with the same version on confluent's maven repo. Here, I was building a SNAPSHOT version but confluent only publishes final versions of the libs to their repo. So you I needed to get that lib in my local maven repo.
Note: I also had to `./gradlew installAll` the last kafka version to build `common`
